[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlengine"
version = "0.1.0"
description = "A unified, high-performance Machine Learning Framework with native C++ backends"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scikit-learn",
    "knn-engine-core"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mlengine*"]